image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_depth: 5

install:
  - git submodule update --init --recursive

platform: Any CPU
configuration:
  - Debug
  - Release


build:
  parallel: true
  project: VectorTileCs.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

  # MSBuild verbosity level
  verbosity: detailed
